---
# handlers file for provision/roles/keepalived

- name: start keepalived
  service:
    name: keepalived
    state: started

- name: restart keepalived
  service:
    name: keepalived
    state: restarted
    enabled: yes

