---
# tasks file for provision/roles/pmm-server

- name: install prerequisites packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
      - python-setuptools
    state: present

- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
  notify: start docker

- name: force all notified handlers to run at this point
  meta: flush_handlers

- name: create pmm-data container
  command: docker create --volume /srv --name pmm-data percona/pmm-server:2 /bin/true

- name: create pmm-server container
  command: docker run --detach --restart always --publish 443:443 --volumes-from pmm-data --name pmm-server percona/pmm-server:2
