---
# tasks file for provision/roles/redis

- name: install redis packages
  yum:
    name: redis
    state: present

- name: configure redis
  copy:
    src: redis.conf
    dest: "/etc/redis.conf"
    owner: root
    group: root
    mode: 0644
    force: true
  notify: restart redis-server

- name: add user nginx to group redis
  user:
   name:   "nginx"
   groups: redis

- name: start and enable redis
  systemd:
    name:    redis
    state:   started
    enabled: true

