---
# tasks file for provision/roles/ssl

- name: create ssl dir
  file:
    path: "{{ haproxy_certs_dir }}"
    state: directory

- name: use the pre-defined DH groups ffdhe4096 recommended by the IETF in [RFC 7919 https://tools.ietf.org/html/rfc7919]
  copy:
    dest: "{{ haproxy_certs_dir }}/dhparam.pem"
    owner: root
    group: root
    mode:  0644
    content: |
      -----BEGIN DH PARAMETERS-----
      MIICCAKCAgEA//////////+t+FRYortKmq/cViAnPTzx2LnFg84tNpWp4TZBFGQz
      +8yTnc4kmz75fS/jY2MMddj2gbICrsRhetPfHtXV/WVhJDP1H18GbtCFY2VVPe0a
      87VXE15/V8k1mE8McODmi3fipona8+/och3xWKE2rec1MKzKT0g6eXq8CrGCsyT7
      YdEIqUuyyOP7uWrat2DX9GgdT0Kj3jlN9K5W7edjcrsZCwenyO4KbXCeAvzhzffi
      7MA0BM0oNC9hkXL+nOmFg/+OTxIy7vKBg8P+OxtMb61zO7X8vC7CIAXFjvGDfRaD
      ssbzSibBsu/6iGtCOGEfz9zeNVs7ZRkDW7w09N75nAI4YbRvydbmyQd62R0mkff3
      7lmMsPrBhtkcrv4TCYUTknC0EwyTvEN5RPT9RFLi103TZPLiHnH1S/9croKrnJ32
      nuhtK8UiNjoNq8Uhl5sN6todv5pC1cRITgq80Gv6U93vPBsg7j/VnXwl5B0rZp4e
      8W5vUsMWTfT7eTDp5OWIV7asfV9C1p9tGHdjzx1VA0AEh/VbpX4xzHpxNciG77Qx
      iu1qHgEtnmgyqQdgCpGBMMRtx3j5ca0AOAkpmaMzy4t6Gh25PXFAADwqTs6p+Y0K
      zAqCkc3OyX3Pjsm1Wn+IpGtNtahR9EGC4caKAH5eZV9q//////////8CAQI=
      -----END DH PARAMETERS-----

- name: upgrade pip
  pip:
    name: pip==8.1.2
    state: forcereinstall

- name: upgrade setuptools
  pip:
    name: setuptools==44.1.1
    state: forcereinstall

- name: install pip pyOpenSSL
  pip:
    name: 
      - cffi==1.14.3
      - pyOpenSSL==21.0.0
      - cryptography==3.2.0
    state: present

- name: generate an openssl private key with the default values
  openssl_privatekey:
    path: "{{ haproxy_certs_dir }}/key.pem"

- name: generate an openssl certificate signing request
  openssl_csr:
    path: "{{ haproxy_certs_dir }}/cert.csr"
    privatekey_path: "{{ haproxy_certs_dir }}/key.pem"
    common_name: "{{ fqdn }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ haproxy_certs_dir }}/cert.pem"
    privatekey_path: "{{ haproxy_certs_dir }}/key.pem"
    csr_path: "{{ haproxy_certs_dir }}/cert.csr"
    provider: selfsigned

- name: create assemble dir
  file:
    path: "{{ haproxy_prep_dir }}"
    state: directory

- name: move cert.pem
  copy:
    remote_src: yes
    src: "{{ haproxy_certs_dir }}/cert.pem"
    dest: "{{ haproxy_prep_dir }}/1-cert.pem"

- name: move key.pem
  copy:
    remote_src: yes
    src: "{{ haproxy_certs_dir }}/key.pem"
    dest: "{{ haproxy_prep_dir }}/2-key.pem"

- name: assemble bundle ssl cert from fragments
  assemble:
    src: "{{ haproxy_prep_dir }}"
    dest: "{{ haproxy_certs_dir }}/nc.example.org.pem"

