---
# defaults file for provision/roles/nginx
fqdn: 'nc.example.org'
# dns resolver (nginx reverse ip lookup) set to 127.0.0.1
# see http://blog.zorinaq.com/nginx-resolver-vulns/
nginx_resolver: '127.0.0.1'

